### ISSUE TITLE
Sending attachment ?

### ISSUE THREAD

**Issue by vkkan** [shaljam/libsignal-protocol-javascript-example#1]
Hi @shaljam  Is there a way to share file between users ? i.e. sending attachments between users , if you know any example implementation pls share

**Comment by shaljam** [comment]
@vkkan I don't have an example. But it should be quite straightforward. Just encrypt the bytes instead of strings.

**Comment by vkkan** [comment]
> @vkkan I don't have an example. But it should be quite straightforward. Just encrypt the bytes instead of strings.

Ok Thanks
